on:
  schedule:
    - cron: "0 0 * * *" # daily
  push:
    branches:
      - master  # Set a branch to deploy
      - develop # Note has logic around deployment

name: build

jobs:
  production:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GH_OPENPHARMA }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2


      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()


# IF develop
      - name: Build dev
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          OPENPHARMA_AWS_ACCESS_KEY_ID: ${{ secrets.OPENPHARMA_AWS_ACCESS_KEY_ID }}
          OPENPHARMA_AWS_SECRET_ACCESS_KEY: ${{ secrets.OPENPHARMA_AWS_SECRET_ACCESS_KEY }}
          OPENPHARMA_AWS_DEFAULT_REGION: ${{ secrets.OPENPHARMA_AWS_DEFAULT_REGION }}
          OPENPHARMA_PAT: ${{ secrets.OPENPHARMA_PAT }}
        run: |
          snakemake -j2  -F python_icon_readme
          
          
        
# IF main
      - name: Build prod 
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          OPENPHARMA_AWS_ACCESS_KEY_ID: ${{ secrets.OPENPHARMA_AWS_ACCESS_KEY_ID }}
          OPENPHARMA_AWS_SECRET_ACCESS_KEY: ${{ secrets.OPENPHARMA_AWS_SECRET_ACCESS_KEY }}
          OPENPHARMA_AWS_DEFAULT_REGION: ${{ secrets.OPENPHARMA_AWS_DEFAULT_REGION }}
          OPENPHARMA_PAT: ${{ secrets.OPENPHARMA_PAT }}
        run: |
          snakemake -j2  -F all
          mkdir build
          cp index.html ./build
          cp os-health.html ./build
          
      - name: Deploy site 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
